on:
    workflow_call: 

jobs:
    Wireguard-test:
        runs-on: ubuntu-24.04
        steps:
        -  name: Network container
           working-directory: /Wireguard/container_pihole_vpn
           run: docker compose up -d

        -  name: Test PiHole Container

        -  name: Test Wireguard Container

        -  name: Test both containers
        
