on:
    workflow_call: 

defaults:
    run:
        working-directory: /Wireguard/container_pihole_vpn
jobs:
    Wireguard-test:
        runs-on: ubuntu-24.04
        steps:
        -  name: Network container
           run: docker compose up -d

        -  name: Test PiHole Container

        -  name: Test Wireguard Container

        -  name: Test both containers

        -  name: Tear down the containers   
           run: docker compose down
        
